### ISSUE TITLE
Slash command "all-commands" not working

### ISSUE THREAD

**Issue by rafidirg** [discordx-ts/templates#78]
I was exploring this template for my discord bot project. when I use \all-commands it seems break the bot and giving this error. I'm new to discordx and discordjs modules. Could you fix this issue? thank you

```
C:\Projects\mainyuk\node_modules\@sapphire\shapeshift\src\validators\ArrayValidator.ts:21
export class ArrayValidator<T extends unknown[], I = T[number]> extends BaseValidator<T> {
             ^
CombinedPropertyError: Received one or more errors
    at ArrayValidator.handle (C:\Projects\mainyuk\node_modules\@sapphire\shapeshift\src\validators\ArrayValidator.ts:21:14)
    at ArrayValidator.parse (C:\Projects\mainyuk\node_modules\@sapphire\shapeshift\src\validators\BaseValidator.ts:102:48)
    at EmbedBuilder.addFields (C:\Projects\mainyuk\node_modules\@discordjs\builders\src\messages\embed\Embed.ts:23:31)
    at file:///C:/Projects/mainyuk/src/commands/slashes.ts:23:10
    at Array.map (<anonymous>)
    at SlashExample.pages (file:///C:/Projects/mainyuk/src/commands/slashes.ts:18:28)
    at next (file:///C:/Projects/mainyuk/node_modules/discordx/src/decorators/classes/Method.ts:85:63)
    at file:///C:/Projects/mainyuk/node_modules/discordx/src/decorators/classes/Method.ts:108:31
    at DApplicationCommand.<anonymous> (file:///C:/Projects/mainyuk/node_modules/discordx/src/decorators/classes/Method.ts:40:49)
    at Client.executeCommandInteraction (file:///C:/Projects/mainyuk/node_modules/discordx/src/Client.ts:1064:31) {
  errors: [ [ 0, [CombinedPropertyError] ] ]
}
```
edit: The issue appears in the 1-starter template

**Comment by oceanroleplay** [comment]
`@sapphire\shapeshift` bug aka `discord.js`.

I have tested raw embed, it's working fine. You can reproduce this issue with `EmbedBuilder`.

**Comment by oceanroleplay** [comment]
**Not working**

```ts
      const embed = new EmbedBuilder()
        .setFooter({ text: `Page ${i + 1} of ${commands.length}` })
        .setTitle("**Slash command info**")
        .addFields({ name: "Name", value: cmd.name })
        .addFields({ name: "Description", value: cmd.description });
```

**Working**

```ts
      const embed = new EmbedBuilder({
        fields: [
          { name: "Name", value: cmd.name },
          { name: "Description", value: cmd.description },
        ],
      })
        .setFooter({ text: `Page ${i + 1} of ${commands.length}` })
        .setTitle("**Slash command info**");
```
